=== jgm99/sandbox-jgm99/xml-parsing-with-xslt-jgm99/src/main/resources/message.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT Mensajes (Mensaje*)>
<!-- Este es el DTD de Edit_Mensaje -->
<!ELEMENT Mensaje (Remitente, Destinatario, Texto)*>
<!ELEMENT Remitente (Nombre, Mail)>
<!ELEMENT Destinatario (Nombre, Mail)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Mail (#PCDATA)>
<!ELEMENT Texto (Asunto, Parrafo)>
<!ELEMENT Asunto (#PCDATA)>
<!ELEMENT Parrafo (#PCDATA)>

=== jgm99/sandbox-jgm99/xml-parsing-with-xslt-jgm99/src/main/resources/message.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<Mensajes>
    <!-- <!DOCTYPE Mensajes SYSTEM "message.dtd">-->
    <Mensaje>
        <Remitente>
            <Nombre>Nombre del remitente</Nombre>
            <Mail> Correo del remitente </Mail>
        </Remitente>
        <Destinatario>
            <Nombre>Nombre del destinatario</Nombre>
            <Mail>Correo del destinatario</Mail>
        </Destinatario>
        <Texto>
            <Asunto>
                Este es mi documento con una estructura muy sencilla
                no contiene atributos ni entidades...
            </Asunto>
            <Parrafo>
                Este es mi documento con una estructura muy sencilla
                no contiene atributos ni entidades...
            </Parrafo>
        </Texto>
    </Mensaje>
</Mensajes>
